### ISSUE TITLE
Re initialization after adding dynamic inputs

### ISSUE THREAD

**Issue by hectorAmaral** [hsnaydd/validetta#34]
Hi guys.

Is there a way to refresh the plugin once it is initialized?
I'm trying to add some dynamic inputs on my form, but realTime validation is not working on new inputs,
and if I call again $('form').validetta({..}) it creates multiple instances of validetta class (new Validetta( this, options )), so I'm getting multiple onValid and onError methods for each instance.

Hope you can help.
Thanks.

**Comment by hsnayd** [comment]
Hi @hectorAmaral 
Validetta does not support external access yet, but Im working on it. Probably you can do this with v1.0.2.

**Comment by arfa2** [comment]
I am not sure exactly what you are after but here is something I extracted from my current work...
http://bodhinyanarama.net.nz/temp/dynamicFields.htm
You can put anything in the $("#prevInfo").html('...'); and adjust data collection accordingly.

The basic logic is to give validetta what is needs - an entry in the field.
I haven't tested it with checkboxes or radio but the principle seems workable - could even be a hidden input that is checked for the 'no' scenario.

I hope this might be of use.

**Comment by hsnaydd** [comment]
This can be followed #44.
