### ISSUE TITLE
realTime:  how to validate on keyup rather than input blur?

### ISSUE THREAD

**Issue by oshihirii** [hsnaydd/validetta#43]
At the moment, the `realTime` setting seems to only trigger validation when clicking outside of the input (possibly `blur`?).  

How to make validation occur on keyup?

**Comment by oshihirii** [comment]
I changed:

`$( this.form ).find('[data-validetta]').not('[type=checkbox]').on( 'change', function( e )`

to:

`$( this.form ).find('[data-validetta]').not('[type=checkbox]').on( 'keyup', function( e )`

Seems to work.  

At:

https://github.com/hsnaydd/validetta/blob/master/dist/validetta.js#L231

**Comment by hsnaydd** [comment]
Hi @oshihirii 
Your solution right, It should work properly.

**Comment by hsnaydd** [comment]
It can be followed #44.

**Comment by oshihirii** [comment]
Have noticed that in a scenario where jQuery UI Autocomplete is used with a regex validetta rule - when the suggested option is chosen, the validetta error message does not disappear (even though the regex rule is satisfied).  So it is confusing that a valid option is chosen but the error message is still displayed.  

I have tried changing the above referenced line to:

    $( this.form ).find('[data-validetta]').not('[type=checkbox]').on( 'change keyup blur', function( e ) {

But it doesn't seem to capture the `change` event when the option is selected.

**Comment by oshihirii** [comment]
FYI, I ended up doing this in the `select: function( event, ui ) {` area:  

    $("#my_selector").next(".validetta-inline").remove(); 

It removes the error span when a valid option is selected from the autocomplete (but the error span will come back if the value is manually changed to an invalid value).

**Comment by hsnaydd** [comment]
Hi @oshihirii
 
Check the issue #51 which related with jQuery Autocomplete plugin

Thank you
