### ISSUE TITLE
Triggering error manually works, but the class is not changed

### ISSUE THREAD

**Issue by bersujamu** [hsnaydd/validetta#45]
`validettaObj.window.open.call(validettaObj, inputElement, errorMessage);` this triggers error manually & it works very nice.
But the parent element still uses `validetta-valid` instead of `validetta-error`. Not big issue, but i think would be nice if it can be fixed from the library instead of patching it manually.

**Comment by hsnaydd** [comment]
Hi @bersujamu 
I know about that. It will be fixed in the next version.

Thank you

**Comment by hsnaydd** [comment]
This can be followed #44.
