### ISSUE TITLE
Destroy instance

### ISSUE THREAD

**Issue by bersujamu** [hsnaydd/validetta#46]
Hi Hasan,

Really like you plugin. Sometime, i need to destroy validetta. But couldn't find it on docs. Is there any way to destroy/ delete/ clear the instance?

Thanks!

**Comment by hsnaydd** [comment]
Hi @bersujamu 

This feature is not available for the moment. Now Im working on version 2. Probably this features are will be added in the version 2.1.

Thanks!

**Comment by hsnaydd** [comment]
It can be followed #44.

**Comment by oshihirii** [comment]
I also need to destroy validetta before re-initialization, i have come across this article, but haven't been able to get it to work yet - but perhaps it will assist in building the feature?  http://ub4.underblob.com/remove-jquery-plugin-instance/

**Comment by oshihirii** [comment]
Update:  

Actually, using the following (from the above link) seems to have destroyed the instances (or, more specifically, it has prevented validetta from running several times on form submit (as all the instances I created validated the form before it was sent)):

```
var destroyCrappyPlugin = function($elem, eventNamespace) {
    var isInstantiated  = !! $.data($elem.get(0));
 
    if (isInstantiated) {
        $.removeData($elem.get(0));
        $elem.off(eventNamespace);
        $elem.unbind('.' + eventNamespace);
    }
};
```

Called with:

```
// BEGIN destroy validetta
var $validetta_element = $("#my_selector");
destroyCrappyPlugin($validetta_element); 
// END destroy validetta
```
