### ISSUE TITLE
remote compare field values using $_session

### ISSUE THREAD

**Issue by arfa2** [hsnaydd/validetta#47]
Hey Hasan. I got distracted but am back enjoying validetta. Real glad you are still working on it.
How's the knee?

getting up to speed again and my first block...
> a simple sign in form - 2 fields - name/email
I need to test both fields against the database and check that they are a matched pair.
emails are unique but there could be more than one "Bob" registered. I could just rely on testing the email address but I would like the extra security (admittedly low level) of testing against the name.
Here is my code - where 'first' is the firstName
```javascript
    $datafile = 'test_news.db';
    $record = file($datafile);
    $rec = count($record);
    if(isset($_POST['first'])) { $fname = strtolower($_POST['first']);
    for ($i=1; $i<$rec; $i++) { $row = explode("|",$record[$i]);
    if (strtolower($row[0])==$fname) { 
    $_SESSION['fName'] = $fname;
    $response = array( 'valid' => true ); break; } // match
    elseif (strtolower($row[0])!=$fname) { // no name match
    $_SESSION['fName'] = 'badName';
    $response = array( 'valid' => false, 'message' => 'Name not found' ); }
    } // END for loop
    }
    if(isset($_POST['email'])) { $mail = strtolower($_POST['email']);
    if(isset($_SESSION['fName']) && $_SESSION['fName']!='badName') { $loginName = $_SESSION['fName']; }
    else { $loginName='eitherBadOrEmpty'; }
    for ($i=1; $i<$rec; $i++) { $row = explode("|",$record[$i]);
    if ( strtolower($row[2]) == $mail ) {  // match
    if (strtolower($row[0])!=$loginName) { unset($_SESSION['fName']);
    $response=array('valid'=>false, 'message' => 'Must pair with Name '.$loginName); break; }
    else { $_SESSION['loginEmail'] = $mail; // for use on editing
    $response = array( 'valid' => true ); break; } // ALL OK        
    }
    else { $response = array( 'valid' => false, 'message' => 'Email not found'); }
    } // END for loop
```
My theory is that the fName session should be updated each time that field is modified. It seems not.

I thought that the code alone might reveal my mistake to you. Yes?
I have set a text example of the above >
http://bodhinyanarama.net.nz/news/formTest.php

If you type fName as 'sdfdf' then error = 'Name not found' -- correct
Then type eMail as 'red@red' that error = 'Must pair with Name eitherBadOrEmpty'
Then correct the name to 'Red' - and my logic says this should reset the session value.
Then change the email to 'sdf@asd' - then back to 'red@red' - the error remains the same.

Why does the session not update?

Thanks

**Comment by hsnaydd** [comment]
Hi @arfa2 
I'm alright now, thank you :)

Validetta cache requests. If the new validation is allready validated before, Validetta uses the cached validation. Because the expected results will be the same as always.

Thank you.

**Comment by arfa2** [comment]
I had a feeling it was something like that. This gets into areas beyond my experience.

Is there an override?
Do you have a suggestion as alternative?

**Comment by arfa2** [comment]
I have worked on this a bit more.
For the two-field case, above - I just reversed the fields; put the email first, as this is the fixed point of reference.

My next, similar, situation is comparing two dates - where start date must precede the end date. I think I will need to write a custom function for this - based on your 'equalTo'

There are so many permutations. Validetta is still holding up well. Thanks

**Comment by hsnaydd** [comment]
Hi @arfa2 

I developed a solution for you. Check this commit [60e282756d029342302ff622c51986b2b9993d62].
You can disable cache with this solution and you can download builded version from `workaround-issue-47` branch

Thank you.

**Comment by arfa2** [comment]
Thanks for the code - way cool...
I will work on this through the afternoon.
Izmir - summertime - 30c ? - here in the south - 12 - very cool :)

I am enjoying transiting my forms to Validetta. Fun.

be well.

**Comment by hsnaydd** [comment]
Thank you bro ;)
