### ISSUE TITLE
jumpTo error on submit

### ISSUE THREAD

**Issue by arfa2** [hsnaydd/validetta#50]
Another code suggestion.
When the user clicks 'submit' the page scrolls to any error - in the case of more than one error it jumps to the topmost error.

line 469: add class 'jumpToError'
````
errorObject.className = this.options.errorTemplateClass + ' jumpToError '+this.options.errorTemplateClass + '--' + this.options.bubblePosition;
````
in the docReady jquery
````
$('#guestForm').submit(function() {
$('html, body').animate({
scrollTop: $(".jumpToError").offset().top-22+'px'
}, 1000); 
````
I have tested this in FF - IE - Chrome & Safari and it is consistent.

**Comment by hsnaydd** [comment]
Hi @arfa2 

You dont need to modify source code for doing that. 

Check this [fiddle](https://jsfiddle.net/gLackzkw/2/)

**Comment by arfa2** [comment]
You the man!
I haven't stitched it into my (biggest) form yet but have copied your fiddle and it works offline - sweet.

I am regularly impressed how you have so much functionality worked into Validetta and still kept the code compact. Well done. I see your V2 list almost done. I look forward to seeing the new version.

Thank you.

**Comment by hsnaydd** [comment]
Your welcome, have a nice day :)
