### ISSUE TITLE
validetta with autocomplete

### ISSUE THREAD

**Issue by flavioafc** [hsnaydd/validetta#51]
when I select an item in the jQuery autoComplete list and it lost the focus, the bubble not disappear.
You can see all the fields above it we have Validetta, and everyone is ok (invisible bubble/validated), the problem is just with jQuery AutoComplete labeled **Comprador**.

![image](https://cloud.githubusercontent.com/assets/11509295/18748584/56f9adfe-80a9-11e6-81d8-b5f2e070d25d.png)

**Comment by hsnaydd** [comment]
Hi @flavioafc 

Probably You need to trigger the change event after selection. 

Try this;
```js
$( ".selector" ).autocomplete({
  select: function( event, ui ) {
     $(this).trigger('change');
  }
});
```

**Comment by flavioafc** [comment]
OH, yeah! It works. I forgot that.

Thank you so much!
