### ISSUE TITLE
Displaying bubble relative instead of absolute

### ISSUE THREAD

**Issue by zeckdude** [hsnaydd/validetta#53]
It would be really cool to be have an option to relatively position the bubble instead of absolutely as it is now.

**Comment by hsnaydd** [comment]
Hi @zeckdude 

Did you check out this example? 
[http://lab.hasanaydogdu.com/validetta/demo/inline.html](http://lab.hasanaydogdu.com/validetta/demo/inline.html)

Sory for the late reply, Thank you.

**Comment by zeckdude** [comment]
@hsnaydd One day is very fast in my opinion. Thanks for replying.

Yeah, I actually ended up using that. Thanks for following up.
