### ISSUE TITLE
Long custom validator names don't work

### ISSUE THREAD

**Issue by zeckdude** [hsnaydd/validetta#54]
It seems like the custom validator names are limited to 15 characters, but I can't find any mention of it in the documentation. I'm not really sure why that would be the case. Is there a reason for this or some sort of bug?

Here's my code:

JS:
```
$(document).ready(function() {
        $('#exm1').validetta({
            validators: {
                callback: {
                    visibleRequired: {
                        callback:  function( el, value ) {
                          return false
                        },
                        errorMessage: "This message shows."
                    },
                    visibleRequiredAndSomeMoreWords: {
                        callback:  function( el, value ) {
                          return false
                        },
                        errorMessage: "This message shows does not show."
                    }
                }
            },
            realTime : true
        });
    });
```

HTML:
```
<form id="exm1" method="POST" action="#">
    <div>
        <label>Callback :</label>
        <input type="text" name="callback" data-validetta="callback[visibleRequired]" />
    </div>
    <div>
        <label>Callback :</label>
        <input type="text" name="callback" data-validetta="callback[visibleRequiredAndSomeMoreWords]" />
    </div>
    <button type="submit">Submit</button>
</form>
```

**Comment by hsnaydd** [comment]
Hi @zeckdude 

This issue will be solved in the next version. If you want a solution for the moment, change this line;
[https://github.com/hsnaydd/validetta/blob/master/dist/validetta.js#L16](url)
with this
[https://github.com/hsnaydd/validetta/blob/develop/dist/validetta.js#L18](url)

It is documented [here](http://lab.hasanaydogdu.com/validetta/#checkingMethods). Check the warning block :)

Thank you.

**Comment by zeckdude** [comment]
Oops. I'm sorry. I looked that thing over and over. Thanks for the workaround.
