### ISSUE TITLE
Setting to only apply validation to visible fields

### ISSUE THREAD

**Issue by zeckdude** [hsnaydd/validetta#55]
I have some form fields which are conditionally shown on the page. They only need to be validated against if they are not hidden. Currently validetta will run the validation on them and stop the form from submitting, even if they are hidden.

Is there a setting to only have validation apply to visible fields?

**Comment by hsnaydd** [comment]
Hi @zeckdude 
You should disable the fileds that you dont want to validate. Validetta will not validate the field if the field is disabled.

Thank you.

**Comment by zeckdude** [comment]
@hsnaydd Thanks for the quick reply.

I am hiding and showing the parent element of the form field. So I would need to programmatically disable the containing form field whenever a parent element is hidden or shown?

**Comment by hsnaydd** [comment]
Yes, display hidden does not make sense for the form elements. Check this [link](http://www.w3schools.com/tags/att_input_disabled.asp) for more detail.

> **Tip**: Disabled <input> elements in a form will not be submitted.

**Comment by zeckdude** [comment]
@hsnaydd Yeah, I see what you mean, but it seems like a hassle to have to set the form fields inside an element to disabled every time you show or hide the container element.

**Comment by hsnaydd** [comment]
This can be considered in the next version.

Thank you.
