### ISSUE TITLE
Wrap errors in <p> to allow styling of multiple error messages

### ISSUE THREAD

**Issue by oshihirii** [hsnaydd/validetta#56]
FYI, I changed:

    errors += state +'<br/>';

to:

    errors += "<p>" + state +'</p>';

At:

https://github.com/hsnaydd/validetta/blob/master/dist/validetta.js#L317

Can then style with something like:

```
.validetta-inline p {
    line-height: 22px;
}
```

**Comment by hsnaydd** [comment]
Hi @oshihirii 

Why you need to do this ?
