### ISSUE TITLE
Custom callback validator not firing when input is blank

### ISSUE THREAD

**Issue by christianklemp** [hsnaydd/validetta#61]
I have a custom callback validator that does not fire when I initially submit the form if the input value is blank. My custom validator callback is checking to see if two different inputs are blank (the one the validator is one, and the other I grab in the callback), as at least one is required.

Here's my custom validator callback:
```javascript
...
callback: {
    email: {
        callback: function(el, value) {
            var phone = $('#primaryContactForm input[name="phone"]');
            return !(value === '' && phone.val().trim() === '');
        },
        errorMessage: "You must provide your email address or phone number."
    }
}
...
```

Running version 1.0.1
Google Chrome 59.0.3071.104 on macOS 10.12.4

**Comment by hsnaydd** [comment]
Hi @christianklemp 
Can you show me an example on jsfiddle ?
