### ISSUE TITLE
How about the customer RNUMBER 

### ISSUE THREAD

**Issue by dnqdat** [hsnaydd/validetta#63]
I have a problem that I want to change again RNUMBER .
For example : if (...){
RNUMBER = new RegExp( /^[\-\+]?(\d+|\d+\.?\d+)$/ ),
}else{
RNUMBER = new RegExp( .... ),
}

I have tried many times have not solved

**Comment by hsnaydd** [comment]
Hi @dnqdat 
Can you show me an example on [jsfiddle](jsfiddle.net) ?

**Comment by dnqdat** [comment]
@hsnaydd  
I found a solution : 
RNUMBER = window.location.pathname=="..." ? RNUMBER = new RegExp(/^[\-\+]?(\d+|\d+\?\d+)$/) : RNUMBER = new RegExp(/^[\-\+]?(\d+|\d+\.?\d+)$/),

:D

**Comment by hsnaydd** [comment]
Is your problem solved?

**Comment by hsnaydd** [comment]
Good news  👍 

Have a nice day.
