### ISSUE TITLE
[Q] How I can run code on provided callbacks outside of calling plugin?

### ISSUE THREAD

**Issue by dehghani-mehdi** [hsnaydd/validetta#64]
Hi,

Thanks for the Validetta.

I have multiple forms/pages and I call Validetta like this in some `JS file`:

```
$('form').validetta();
```

Validetta works as expected, but how I can run code on (let's say) `onValid` for current `form`?

I mean something like this:

```
$('#frm-main').validetta('onValid', function(){ ... });
```

Did you implement this?

Thanks.

**Comment by hsnaydd** [comment]
Hi @dehghani-mehdi,

Unfortunately Validetta does not have public api so you cant do this. But I plan rewrite validetta as v3, this kind of things will be included on it.

Thanks.
