### ISSUE TITLE
15 character limit on rule declarations

### ISSUE THREAD

**Issue by jtmdrums** [hsnaydd/validetta#68]
After struggling for a while to figure out why Validetta wasn't working properly with `equalTo` on a particular field, searching for other error sources/duplicate fields etc., I finally resorted to picking apart Validetta itself and found that it wasn't even hitting the `equalTo` code block. Turns out this gem of a line is at the start of the file:
`RRULE = new RegExp( /^(minChecked|maxChecked|minSelected|maxSelected|minLength|maxLength|equalTo|different|regExp|remote|callback)\[(\w{1,15})\]/i ),`

My problematic `equalTo` just happened to be referencing a field name that was 16 characters long, and this regex explicitly tells it to ignore any field name longer than 15. Why on earth is it limited to 15 characters (and not mentioned anywhere in the documentation that this is the case)?

**Comment by hsnaydd** [comment]
Hi @jtmdrums

Actually I don't remember exactly why I put this condition 😊. Maybe there was a reason, I don't know. However, it is mentioned in the documentation

>Warning!
>Validator arguments ( e.g. `input_name`, and `validator_name` ) should be any word character ( letter, number, underscore ) and should not be greater than 15 characters!

**Comment by hsnaydd** [comment]
Hi @jherencia;

I checked this issue again and found that this issue has been solved in version v2.

You can use version [v2](https://github.com/hsnaydd/validetta/tree/v2-dev) or you can use the solution described [here](https://github.com/hsnaydd/validetta/issues/54#issuecomment-254322923). Also, you can check [here](https://github.com/hsnaydd/validetta/tree/v2-dev/docs) for v2 documentation.

Thanks.

**Comment by jtmdrums** [comment]
Ah, I didn't know to look there, I'd expect that kind of restriction to be inline with the description of the validator. Thanks for the info, we'll keep using the edited version for now and look into switching to v2 going forward. Thanks for the info!
